// Mocks generated by Mockito 5.4.6 from annotations
// in report_plant/test/features/plants/domain/usecases/get_all_plants_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:report_plant/core/errors/failures.dart' as _i5;
import 'package:report_plant/features/plants/domain/entities/plant.dart' as _i6;
import 'package:report_plant/features/plants/domain/repositories/plant_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantRepository extends _i1.Mock implements _i3.PlantRepository {
  MockPlantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Plant>>> getAllPlants() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Plant>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Plant>>(
          this,
          Invocation.method(
            #getAllPlants,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Plant>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Plant>> getPlantById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Plant>>.value(
            _FakeEither_0<_i5.Failure, _i6.Plant>(
          this,
          Invocation.method(
            #getPlantById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Plant>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> insertPlant(_i6.Plant? plant) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPlant,
          [plant],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #insertPlant,
            [plant],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePlant(_i6.Plant? plant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updatePlant,
            [plant],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePlant(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deletePlant,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
